CREATE DATABASE IF NOT EXISTS ev_app;
USE ev_app;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(30),
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
select * from users;
CREATE TABLE IF NOT EXISTS trips (
  tripID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  driverID INT UNSIGNED NOT NULL,
  startTime DATETIME NOT NULL,
  endTime DATETIME,
  distance FLOAT,
  avgSpeed FLOAT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (driverID) REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sensor_data (
  sensorID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tripID INT UNSIGNED NOT NULL,
  speed FLOAT,
  acceleration FLOAT,
  latitude DOUBLE,
  longitude DOUBLE,
  timestamp DATETIME NOT NULL,

  FOREIGN KEY (tripID) REFERENCES trips(tripID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS driver_scores (
  scoreID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tripID INT UNSIGNED NOT NULL UNIQUE,
  totalScore INT,
  riskLevel VARCHAR(50),
  suggestion TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (tripID) REFERENCES trips(tripID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS api_sync_log (
  syncID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tripID INT UNSIGNED NOT NULL,
  status VARCHAR(50) NOT NULL,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (tripID) REFERENCES trips(tripID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
select * from trips;
select * from api_sync_log;
select * from driver_scores;
select * from sensor_data;

